In [ ]:
import sqlite3, random
import pandas as pd
from datetime import datetime, timedelta

conn = sqlite3.connect('alpha.db')
cursor = conn.cursor()

schema = '''
    CREATE TABLE IF NOT EXISTS alpha_table (
        timestamp DATE,
        temperature REAL,
        pressure REAL,
        altitude REAL,
        power REAL,
        voltage REAL,
        fuellevel REAL,
        latitude REAL,
        longitude REAL,
        thrust REAL,
        commstatus TEXT,
        enginetemp REAL,
        battvoltage REAL,
        solarpower REAL,
        fuelflow REAL,
        oxygenlevel REAL,
        gyrox REAL,
        gyroy REAL,
        gyroz REAL,
        statusflags TEXT
    )
'''

cursor.execute(schema)

data = []
r=1000
current_time = datetime.now()
ref_time = (current_time - timedelta(minutes=30))

for i in range(r):
    timestamp = (ref_time + timedelta(minutes=i)).strftime('%Y-%m-%d %H:%M:%S')
    row_data = [timestamp] + [random.uniform(10.0, 100.0) for _ in range(19)]
    data.append(tuple(row_data))


cursor.executemany('INSERT INTO alpha_table VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', data)
conn.commit()
conn.close()

conn = sqlite3.connect('alpha.db')
df = pd.read_sql_query('SELECT * FROM alpha_table', conn)
conn.close()

df

,timestamp,temperature,pressure,altitude,power,voltage,fuellevel,latitude,longitude,thrust,commstatus,enginetemp,battvoltage,solarpower,fuelflow,oxygenlevel,gyrox,gyroy,gyroz,statusflags
0,2023-11-11 20:39:36,66.900911,28.312295,79.556003,66.031188,76.839360,15.172864,55.370311,17.119377,23.068937,63.2686009276327,17.962526,40.328483,55.846014,26.188222,70.727085,42.279069,74.373016,91.463178,72.2845862092506
1,2023-11-11 20:40:36,14.483113,39.442592,21.975939,15.635121,74.961544,68.480886,52.233324,37.671542,85.143208,63.0868481764898,81.878360,56.255211,88.093575,35.652814,18.648710,30.687429,61.372896,37.338121,13.2298200259513
2,2023-11-11 20:41:36,54.705320,99.908527,85.592694,97.684949,41.541227,43.161803,33.961799,68.675698,77.704435,84.6415318155168,59.640624,93.366017,20.357109,32.903842,29.328101,38.443747,84.670232,20.665268,88.4579439401356
3,2023-11-11 20:42:36,61.084653,47.801831,72.790230,98.512795,27.587754,27.843916,36.675365,75.944165,51.008269,37.0451659417972,55.764819,51.019576,19.282598,70.786131,59.758493,86.675289,13.074858,80.086191,46.6908940220662
4,2023-11-11 20:43:36,96.314013,24.151760,65.538232,71.785633,11.770776,84.307788,60.083514,72.366794,26.101818,39.985299111237,27.984599,19.590755,18.103858,94.769536,65.611822,38.827829,78.651530,33.685328,20.3101370630907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023-11-12 13:14:36,51.803182,26.091692,21.142764,92.417836,14.360291,25.544233,32.753130,91.033848,73.215365,26.0411021065339,18.071135,13.039891,97.936024,90.016883,36.490652,73.342151,12.148942,50.849193,11.4357665181239
996,2023-11-12 13:15:36,67.898219,13.203776,68.163270,49.881746,32.031091,46.017563,76.418459,25.113004,44.547121,99.7331713203854,83.080095,42.478243,97.591377,33.671060,22.836789,61.845705,44.380207,37.695090,37.1184001702222
997,2023-11-12 13:16:36,75.758484,67.407406,30.040000,85.750734,37.925776,63.427330,29.536302,89.100221,90.782521,87.3298538484602,90.896953,96.780222,11.437337,16.888311,95.961032,20.166162,87.928128,90.862749,47.2070935008101
998,2023-11-12 13:17:36,39.335426,29.240106,35.438209,35.634515,84.437130,19.006378,91.811151,38.460250,65.063337,17.4727383511271,69.352782,48.141496,44.082667,18.469843,56.732555,94.925582,21.775006,99.175772,97.3736567443463
999,2023-11-12 13:18:36,60.591739,90.623132,17.627472,93.652213,88.406865,46.261598,25.727508,29.645187,95.234474,76.9120381520387,91.645594,17.471064,90.477141,57.158794,81.424757,43.387875,15.671343,89.228397,41.3024292871358

In [ ]:
import sqlite3, random
import pandas as pd
from datetime import datetime, timedelta


conn = sqlite3.connect('beta.db')
cursor = conn.cursor()


schema = '''
    CREATE TABLE IF NOT EXISTS beta_table (
        timestamp DATE,
        temperature REAL,
        pressure REAL,
        altitude REAL,
        power REAL,
        voltage REAL,
        fuellevel REAL,
        latitude REAL,
        longitude REAL,
        thrust REAL,
        commstatus TEXT,
        enginetemp REAL,
        battvoltage REAL,
        solarpower REAL,
        fuelflow REAL,
        oxygenlevel REAL,
        gyrox REAL,
        gyroy REAL,
        gyroz REAL,
        statusflags TEXT
    )
'''


cursor.execute(schema)

data = []
r=1000
current_time = datetime.now()
ref_time = (current_time - timedelta(minutes=30))

for i in range(r):
    timestamp = (ref_time + timedelta(minutes=i)).strftime('%Y-%m-%d %H:%M:%S')
    row_data = [timestamp] + [random.uniform(10.0, 100.0) for _ in range(19)]
    data.append(tuple(row_data))

cursor.executemany('INSERT INTO beta_table VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', data)
conn.commit()
conn.close()

conn = sqlite3.connect('beta.db')
df = pd.read_sql_query('SELECT * FROM beta_table', conn)
conn.close()

df

,timestamp,temperature,pressure,altitude,power,voltage,fuellevel,latitude,longitude,thrust,commstatus,enginetemp,battvoltage,solarpower,fuelflow,oxygenlevel,gyrox,gyroy,gyroz,statusflags
0,2023-11-11 20:39:36,26.827391,45.417902,78.426160,92.939431,58.093356,70.696828,71.328633,55.217301,50.201982,75.1406784682887,72.161727,40.257387,36.927562,49.775486,19.050912,86.541502,94.603414,32.169174,79.2714178923178
1,2023-11-11 20:40:36,86.905546,44.071082,68.053205,46.625929,50.752088,97.400804,15.903844,53.025616,20.806608,53.3514275475259,44.396849,14.703100,78.548041,84.224484,15.020310,21.688158,55.455362,98.299134,20.3594544111839
2,2023-11-11 20:41:36,87.886466,87.820530,54.381103,45.094881,10.562027,71.878930,24.411288,65.060313,12.788466,96.0469948736533,71.768405,89.977719,73.191113,21.934854,10.525971,18.584139,28.199506,22.508829,87.0637066208373
3,2023-11-11 20:42:36,76.303098,64.436765,44.157601,96.577069,68.317166,67.782427,20.157101,38.594337,50.365155,18.7032419587461,34.879614,96.312578,64.415737,34.504947,20.095177,58.318608,90.704916,44.790093,79.5157467572341
4,2023-11-11 20:43:36,89.548544,59.614047,98.219983,74.201251,74.766125,41.466613,71.333254,23.978887,51.303674,50.9966681593216,99.321720,81.333521,89.208026,17.489457,81.289329,16.007308,75.958382,83.052527,92.0657408731202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023-11-12 13:14:36,22.750714,59.944514,65.420453,95.124436,47.687276,98.449034,43.751041,79.650598,26.757610,23.3288408486783,77.165282,95.329209,54.422390,43.561446,80.303974,77.647971,50.275635,74.867729,70.7424511792158
996,2023-11-12 13:15:36,71.507653,96.314129,78.466491,18.484817,52.272585,64.107600,14.131225,30.023884,82.059726,72.4840196769185,95.364529,71.963656,27.623117,73.113470,84.764649,32.765108,15.856724,87.631617,36.51381079118
997,2023-11-12 13:16:36,33.895996,83.589452,73.539010,35.314912,88.284260,94.340361,57.055426,55.498596,91.794048,32.6626813747873,99.851297,60.936250,28.893583,19.661567,93.748495,35.866234,32.761632,95.445115,68.1246430517776
998,2023-11-12 13:17:36,95.701828,23.101308,84.036786,94.838847,93.098078,33.421714,77.246793,86.927108,13.539954,24.769000382127,76.393278,24.851284,65.403982,81.276150,60.688884,64.009899,95.958512,10.347301,47.5238332163627
999,2023-11-12 13:18:36,48.959801,75.075374,54.252737,80.365270,30.209073,63.216025,67.937856,52.071189,35.615434,65.8486704159197,61.010756,37.879081,15.885566,41.613493,13.275292,78.371896,81.185591,90.063455,76.8528583823984

In [ ]:
import sqlite3, random
import pandas as pd
from datetime import datetime, timedelta

conn = sqlite3.connect('gamma.db')
cursor = conn.cursor()

schema = '''
    CREATE TABLE IF NOT EXISTS gamma_table (
        timestamp DATE,
        temperature REAL,
        pressure REAL,
        altitude REAL,
        power REAL,
        voltage REAL,
        fuellevel REAL,
        latitude REAL,
        longitude REAL,
        thrust REAL,
        commstatus TEXT,
        enginetemp REAL,
        battvoltage REAL,
        solarpower REAL,
        fuelflow REAL,
        oxygenlevel REAL,
        gyrox REAL,
        gyroy REAL,
        gyroz REAL,
        statusflags TEXT
    )
'''

cursor.execute(schema)
data = []
r=1000
current_time = datetime.now()
ref_time = (current_time - timedelta(minutes=30))

for i in range(r):
    timestamp = (ref_time + timedelta(minutes=i)).strftime('%Y-%m-%d %H:%M:%S')
    row_data = [timestamp] + [random.uniform(10.0, 100.0) for _ in range(19)]
    data.append(tuple(row_data))

cursor.executemany('INSERT INTO gamma_table VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', data)
conn.commit()
conn.close()

conn = sqlite3.connect('gamma.db')
df = pd.read_sql_query('SELECT * FROM gamma_table', conn)
conn.close()

df

,timestamp,temperature,pressure,altitude,power,voltage,fuellevel,latitude,longitude,thrust,commstatus,enginetemp,battvoltage,solarpower,fuelflow,oxygenlevel,gyrox,gyroy,gyroz,statusflags
0,2023-11-11 20:39:36,73.314418,97.494252,98.657768,23.653453,43.667997,16.484640,17.183005,92.008485,90.339724,29.0854303636171,45.481543,91.295297,92.225635,26.990627,59.833815,29.703862,87.406410,92.716000,47.0858072561488
1,2023-11-11 20:40:36,30.846565,53.552353,80.684063,43.864611,84.320872,34.771903,88.548908,61.013283,21.718221,33.3102878523248,46.973080,23.596192,79.853683,11.281284,94.626828,97.926371,32.596510,28.901320,81.7127360485176
2,2023-11-11 20:41:36,58.945050,76.665360,72.110481,44.936388,10.783227,90.828731,47.947332,41.199647,94.293512,28.3202355334948,10.165291,99.541208,63.755801,14.064331,51.655481,45.888129,95.208445,34.623523,46.0369564282149
3,2023-11-11 20:42:36,89.391632,68.171694,58.086751,37.062204,84.872893,94.308972,67.950617,22.783778,87.244293,72.0782675049371,92.981851,46.392610,76.716698,38.233812,72.341947,97.719155,73.660729,62.608138,70.0862184613457
4,2023-11-11 20:43:36,96.536843,62.083642,95.103143,15.073646,81.522772,36.808822,51.850183,19.504730,78.206277,88.797340658029,75.067191,37.646484,91.101532,44.573942,77.690653,50.515440,96.559869,44.954934,70.326718033127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023-11-12 13:14:36,98.343676,10.154039,67.437848,35.873395,88.686134,64.992055,77.922120,89.337152,72.829624,58.6377691023033,96.445556,50.971932,70.894418,28.594114,34.177240,68.365529,64.081948,19.503167,18.1364065372888
996,2023-11-12 13:15:36,71.415843,76.165106,49.465337,54.122077,16.875970,26.163847,40.358959,24.681527,58.555151,21.7185452049646,81.153396,62.105944,86.376247,42.466406,34.284082,90.835674,34.871287,46.292572,54.699929888253
997,2023-11-12 13:16:36,68.106957,10.986818,73.882584,12.508724,42.336428,20.260584,28.129290,91.670768,74.959878,69.0871647690918,34.711121,73.194906,98.185735,56.934054,24.827587,35.473548,45.507464,50.363921,47.3227939391985
998,2023-11-12 13:17:36,92.647367,25.028611,76.602384,91.297838,61.245058,76.564615,87.830112,97.587192,76.353235,52.9592585081887,29.734324,47.409379,36.482675,99.276432,37.743471,52.109275,45.952237,97.935625,71.1348133694882
999,2023-11-12 13:18:36,31.055209,28.975490,77.248593,69.296695,49.329145,33.059230,45.404930,93.449091,32.801447,21.6538092043372,86.791167,63.702740,66.418311,60.907749,90.771410,71.209199,11.634518,73.011572,79.5049418031955